const fs = require('node:fs');
const { categories, services } = require('./content-v5.cjs');

const site = 'https://sefiro888.github.io/ejemplo1lumis/';
const phone = '34652609338';
const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const icon = (name, size = 20) => {
  const paths = {
    arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',
    north:'<path d="M6 18 18 6M7 6h11v11"/>',
    phone:'<path d="m6 3 3 5-2 2a15 15 0 0 0 7 7l2-2 5 3c-.3 2-1.7 3-4 3C9 21 3 15 3 7c0-2 1-3.2 3-4Z"/>',
    pin:'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
    sparkle:'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5L12 2Z"/>',
    plus:'<path d="M12 5v14M5 12h14"/>',
    menu:'<path d="M3 8h18M3 16h18"/>',
    close:'<path d="M5 5l14 14M19 5 5 19"/>',
    instagram:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".5" fill="currentColor"/>'
  };
  return `<svg class="icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;
};
const photo = (name, alt, cls = '', eager = false) => `<img class="${cls}" src="assets/images/${name}.jpg" srcset="assets/images/${name}-sm.jpg 640w, assets/images/${name}.jpg 1536w" sizes="(max-width: 760px) 100vw, 50vw" alt="${esc(alt)}" width="1536" height="1024" loading="${eager?'eager':'lazy'}" decoding="async"${eager?' fetchpriority="high"':''}>`;
const wa = message => `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
const bySlug = slug => services.find(service => service.slug === slug);
const link = (href, label, className = 'text-link') => `<a class="${className}" href="${href}">${label} ${icon('north',18)}</a>`;

function head(title, description, path, image = 'hero-humano') {
  return `<!doctype html>
<html lang="es"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#0a2a5a"><meta name="description" content="${esc(description)}">
<link rel="canonical" href="${site}${path}"><link rel="preload" href="assets/fonts/manrope-variable.ttf" as="font" type="font/ttf" crossorigin>
<meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${site}assets/images/${image}.jpg">
<title>${esc(title)}</title><link rel="stylesheet" href="assets/css/site.css?v=5"><script src="assets/js/site.js?v=5" defer></script>
</head><body><a class="skip-link" href="#main">Saltar al contenido</a>`;
}
function header(active = '') {
  return `<div class="utility"><span>${icon('pin',14)} Zaragoza · Cerca de tus espacios</span><a href="tel:+34652609338">${icon('phone',14)} 652 63 09 38</a></div>
<header class="header"><div class="header-inner">
<a class="logo" href="index.html" aria-label="Limpiezas Lumis, inicio"><img src="assets/images/logo.png" alt="Limpiezas Lumis" width="2100" height="749"></a>
<button class="menu-button" type="button" aria-expanded="false" aria-controls="main-nav"><span>Menú</span>${icon('menu',22)}</button>
<nav class="main-nav" id="main-nav" aria-label="Navegación principal"><a href="index.html"${active==='home'?' aria-current="page"':''}>Inicio</a>
<details class="nav-dropdown"><summary>Servicios <span>${icon('plus',17)}</span></summary><div class="nav-panel"><div class="nav-panel-intro"><small>ENCUENTRA TU SERVICIO</small><strong>Un espacio.<br><em>Muchas formas de cuidarlo.</em></strong><p>Elige por dónde quieres empezar.</p>${link('index.html#servicios','Explorar todos los servicios')}</div><div class="nav-panel-groups">${categories.map(c=>`<div><span class="nav-group-title">${esc(c.name)}</span>${services.filter(s=>s.category===c.id).map(s=>`<a href="${s.slug}.html">${esc(s.name)} ${icon('arrow',14)}</a>`).join('')}</div>`).join('')}</div></div></details>
<a href="index.html#como-empezar">Cómo empezar</a><a href="index.html#lumis">Lumis</a><a class="nav-contact" href="index.html#contacto">Pedir presupuesto ${icon('north',17)}</a></nav>
</div></header>`;
}
function footer(current = '') {
  return `<footer class="footer" id="pie"><div class="footer-top"><div class="footer-intro"><span class="eyebrow light">¿LO VEMOS CONTIGO?</span><h2>Ese espacio<br><em>puede cambiar.</em></h2><p>Cuéntanos dónde estás y qué necesitas. La conversación empieza por ahí.</p><a class="button button-lime" href="${wa('Hola, he visto la web de Limpiezas Lumis y quería consultar un presupuesto en Zaragoza.')}" target="_blank" rel="noopener">Escribir por WhatsApp ${icon('north',19)}</a></div><div class="footer-contact"><span class="eyebrow light">LIMPIEZAS LUMIS · ZARAGOZA</span><a class="footer-phone" href="tel:+34652609338">652 63 09 38</a><a href="tel:+34976053543">976 05 35 43</a><a href="mailto:lumis.arellano25@gmail.com">lumis.arellano25@gmail.com</a><a href="https://www.instagram.com/lumis.arellano25/" target="_blank" rel="noopener">${icon('instagram',19)} Ver más de Lumis en Instagram</a></div></div>
<div class="footer-directory"><div class="footer-brand"><img src="assets/images/logo.png" alt="Limpiezas Lumis" width="2100" height="749"><p>Deja tus espacios relucientes.<br>Espacios limpios, vidas mejores.</p></div>${categories.map(c=>`<div><h3>${esc(c.name)}</h3>${services.filter(s=>s.category===c.id).map(s=>`<a href="${s.slug}.html"${current===s.slug?' aria-current="page"':''}>${esc(s.name)}</a>`).join('')}</div>`).join('')}</div><div class="footer-bottom"><span>© Limpiezas Lumis · Zaragoza</span><span>Imágenes ilustrativas creadas para esta demostración; no muestran trabajos reales de Lumis.</span><a href="#main">Volver arriba ↑</a></div></footer><a class="float-wa" href="${wa('Hola, he visto la web de Limpiezas Lumis. Quería contaros qué espacio necesito cuidar.')}" target="_blank" rel="noopener" aria-label="Hablar con Limpiezas Lumis por WhatsApp">${icon('phone',20)} <span>Hablemos</span></a></body></html>`;
}
function serviceRow(service) {
  return `<a class="service-row" href="${service.slug}.html" data-service="${esc((service.name+' '+service.lead).toLowerCase())}"><span class="row-num">${service.number}</span><span class="row-title">${esc(service.name)}${service.tentative?'<small>Consultar disponibilidad</small>':''}</span><span class="row-phrase">${esc(service.hero)}</span><span class="row-arrow">${icon('north',22)}</span></a>`;
}
function compare(before, after, title) {
  return `<div class="compare" style="--split:50%"><div class="compare-image compare-before"><img src="assets/images/${before}.jpg" alt="Estado anterior ilustrativo: ${esc(title)}" loading="lazy"><span>Antes</span></div><div class="compare-image compare-after"><img src="assets/images/${after}.jpg" alt="Estado posterior ilustrativo: ${esc(title)}" loading="lazy"><span>Después</span></div><div class="compare-line" aria-hidden="true"><span>↔</span></div><input type="range" min="0" max="100" value="50" aria-label="Deslizar para comparar el antes y el después de ${esc(title)}"><small>Ejemplo visual ilustrativo</small></div>`;
}
function home() {
  const desc='Limpiezas Lumis en Zaragoza. Limpieza para hogares, exteriores, espacios profesionales, suelos y tejidos. Descubre los servicios y consulta por WhatsApp.';
  const html = `${head('Limpiezas Lumis Zaragoza | Espacios para disfrutarlos',desc,'index.html')}${header('home')}
<main id="main"><section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="eyebrow-mark"></span> LIMPIEZAS LUMIS · ZARAGOZA</div><h1>Que dé gusto<br><em>estar aquí.</em></h1><p>Para el lugar donde vives. Para el lugar donde trabajas. Para esos rincones que merecen una nueva mirada.</p><div class="hero-actions"><a class="button button-primary" href="#servicios">Encuentra tu servicio ${icon('north',19)}</a><a class="hero-call" href="${wa('Hola, he visto la web de Limpiezas Lumis y quería contaros qué espacio necesito cuidar.')}" target="_blank" rel="noopener">Hablemos por WhatsApp ${icon('arrow',18)}</a></div><div class="hero-note"><span>01 / 03</span><strong>De Zaragoza. Para tus espacios.</strong></div></div><div class="hero-visual">${photo('hero-humano','Manos limpiando el cristal de una vivienda, escena ilustrativa','hero-image',true)}<div class="hero-visual-caption"><span>DEJA TUS ESPACIOS RELUCIENTES</span><strong>La diferencia se nota.<br><em>La sensación, también.</em></strong></div><div class="hero-image-label">Ejemplo visual ilustrativo</div></div></section>
<div class="marquee" aria-label="Hogar, exterior, espacios profesionales, suelos y tejidos"><div><span>Tu hogar</span>${icon('sparkle',20)}<span>Al aire libre</span>${icon('sparkle',20)}<span>Tu negocio</span>${icon('sparkle',20)}<span>Suelos y tejidos</span>${icon('sparkle',20)}<span>Tu hogar</span>${icon('sparkle',20)}<span>Al aire libre</span>${icon('sparkle',20)}</div></div>
<section class="intro section" id="lumis"><div class="intro-label"><span class="eyebrow">LIMPIEZAS LUMIS</span><span>01 / UNA FORMA DE MIRAR</span></div><div class="intro-main"><h2>Un espacio cuidado<br>se <em>vive de otra manera.</em></h2><div class="intro-bottom"><p>No hablamos solo de lo que se ve. Hablamos de entrar en casa y sentir calma, de abrir un negocio con ganas o de volver a usar esa terraza que habías dejado pendiente.</p><p>Cuéntanos cómo es tu espacio. Te ayudamos a empezar por el servicio que tiene sentido consultar.</p></div></div><div class="intro-side">${photo('lumis-terraza','Limpieza ilustrativa de una mesa en una terraza','',false)}<span>Pequeños gestos. Otra sensación.</span></div></section>
<section class="pathways section" id="espacios"><div class="section-heading"><span class="eyebrow">POR DÓNDE EMPEZAR</span><h2>¿Qué espacio<br><em>quieres cuidar?</em></h2><p>Entra por lo que reconoces. Dentro encontrarás el servicio concreto y qué contarnos para pedir presupuesto.</p></div><div class="path-grid">${categories.map((c,i)=>`<a class="path-card path-${c.id}" href="#${c.id}">${photo(c.image,c.description)}<span class="path-overlay"><small>0${i+1} / ${esc(c.short.toUpperCase())}</small><strong>${esc(c.name)}</strong><span>${esc(c.description)}</span><i>${icon('north',20)}</i></span></a>`).join('')}</div></section>
<section class="services section" id="servicios"><div class="services-heading"><div><span class="eyebrow">NUESTROS SERVICIOS</span><h2>Uno para cada<br><em>necesidad.</em></h2></div><div><p>Explora los 16 servicios. Cada página te explica cuándo puede encajar, qué datos ayudan a preparar la consulta y cómo hablar con Lumis.</p><label class="search-label" for="service-search">Buscar un servicio ${icon('arrow',18)}</label><input id="service-search" type="search" placeholder="Ej. cristales, oficinas, sofá…" autocomplete="off"><p id="search-status" class="search-status" aria-live="polite"></p></div></div>
${categories.map((c,i)=>`<div class="service-group" id="${c.id}"><div class="group-intro"><span>0${i+1} / ${esc(c.short.toUpperCase())}</span><h3>${esc(c.name)}</h3><p>${esc(c.line)}</p>${photo(c.image,c.description)}</div><div class="group-links">${services.filter(s=>s.category===c.id).map(serviceRow).join('')}</div></div>`).join('')}</section>
<section class="editorial section"><div class="editorial-images"><div>${photo('lumis-oficina','Persona limpiando un cristal de una oficina, escena ilustrativa')}</div><div>${photo('general','Persona limpiando una encimera, escena ilustrativa')}</div><span>Imágenes ilustrativas</span></div><div class="editorial-copy"><span class="eyebrow">EL DETALLE IMPORTA</span><h2>Hay cosas que<br>se ven. Otras<br><em>se sienten.</em></h2><p>Una ventana que deja pasar la luz. Un suelo que cambia la percepción de una estancia. Un espacio al que apetece volver.</p>${link('#contacto','Cuéntanos qué necesitas')}</div></section>
<section class="change section"><div class="change-heading"><span class="eyebrow">UNA MIRADA ANTES Y DESPUÉS</span><h2>Desliza.<br><em>Descubre el cambio.</em></h2><p>La misma escena, antes y después, creada para mostrar visualmente el tipo de diferencia que puede apreciarse. No es un trabajo realizado por Lumis.</p>${link('cristales.html','Ver limpieza de cristales')}</div>${compare('cristales-antes','cristales-despues','unos cristales')}</section>
<section class="steps section" id="como-empezar"><div class="steps-heading"><span class="eyebrow">ASÍ DE FÁCIL</span><h2>Una conversación.<br><em>Un buen comienzo.</em></h2></div><div class="step-grid"><article><span>01</span><h3>Cuéntanos el espacio.</h3><p>Casa, negocio o exterior. Dinos dónde está y qué te gustaría cuidar.</p></article><article><span>02</span><h3>Comparte las prioridades.</h3><p>Dimensiones aproximadas, materiales y unas fotografías pueden ayudar a entenderlo.</p></article><article><span>03</span><h3>Hablemos del presupuesto.</h3><p>La conversación continúa directamente con Lumis por WhatsApp, sin compromiso.</p></article></div></section>
<section class="contact section" id="contacto"><div class="contact-copy"><span class="eyebrow light">EMPIEZA POR AQUÍ</span><h2>Tu espacio.<br>Tu historia.<br><em>Hablemos.</em></h2><p>Prepara un primer mensaje en menos de un minuto. Lo revisarás en WhatsApp antes de enviarlo.</p><div class="contact-ways"><a href="tel:+34652609338">${icon('phone',18)} 652 63 09 38</a><a href="mailto:lumis.arellano25@gmail.com">lumis.arellano25@gmail.com</a></div></div><form class="contact-form" id="contact-form"><span class="form-kicker">PREPARA TU CONSULTA</span><label for="form-service">¿Qué servicio te interesa?</label><select id="form-service" name="service">${services.map(s=>`<option value="${s.slug}">${esc(s.name)}</option>`).join('')}</select><label for="form-zone">¿En qué zona está el espacio? <small>(opcional)</small></label><input id="form-zone" name="zone" placeholder="Ej. Zaragoza, Centro" maxlength="100"><label for="form-note">¿Qué te gustaría contarnos? <small>(opcional)</small></label><textarea id="form-note" name="note" rows="4" maxlength="500" placeholder="Tipo de espacio, tamaño aproximado, prioridades…"></textarea><a id="form-wa" class="button button-primary" href="${wa('Hola, quería consultar un servicio de limpieza en Zaragoza.')}" target="_blank" rel="noopener">Continuar en WhatsApp ${icon('north',19)}</a><small class="form-help">El mensaje se prepara aquí. Tú decides si lo envías.</small></form></section>
<section class="instagram section"><div><span class="eyebrow">SÍGUENOS EN INSTAGRAM</span><h2>Un poco más<br><em>de Lumis.</em></h2><p>Descubre su perfil oficial. Estas imágenes son ilustrativas y no representan trabajos realizados por la empresa.</p>${link('https://www.instagram.com/lumis.arellano25/','Ver perfil de Instagram')}</div><div class="insta-photos">${photo('lumis-terraza','Terraza ilustrativa')}${photo('hero-humano','Limpieza de cristal ilustrativa')}${photo('lumis-oficina','Oficina ilustrativa')}</div></section></main>${footer()}`;
  fs.writeFileSync('index.html', html);
}
function page(service) {
  const category = categories.find(c=>c.id===service.category);
  const desc=`${service.subtitle} ${service.lead} Consulta a Limpiezas Lumis por WhatsApp.`;
  const message=`Hola, he visto vuestra página de ${service.name.toLowerCase()} y quería consultar un presupuesto. El espacio está en [zona de Zaragoza]. Se trata de [tipo de espacio] y mide aproximadamente [tamaño]. Puedo enviar fotografías.`;
  const firstImage=service.gallery[0];
  const secondImage=service.gallery[1];
  const html=`${head(`${service.name} en Zaragoza | Limpiezas Lumis`,desc,`${service.slug}.html`,service.image)}${header()}
<main id="main"><div class="breadcrumbs"><a href="index.html">Inicio</a><span>/</span><a href="index.html#${category.id}">${esc(category.name)}</a><span>/</span><span aria-current="page">${esc(service.name)}</span></div>
<section class="service-hero-v5"><div class="service-hero-photo">${photo(service.image,`${service.name} en un espacio ilustrativo`,'',true)}<span>Ejemplo visual ilustrativo</span></div><div class="service-hero-copy"><span class="eyebrow">${esc(category.name.toUpperCase())} / ${service.number} DE 16</span><h1>${esc(service.name)}</h1><p>${esc(service.hero)}</p><a class="button button-lime" href="${wa(message)}" target="_blank" rel="noopener">Consultar este servicio ${icon('north',19)}</a><small>${esc(service.subtitle)}</small></div></section>
<nav class="page-index" aria-label="En esta página"><span>EN ESTA PÁGINA</span><a href="#sobre">El servicio</a><a href="#cuando">Cuándo puede encajar</a>${service.compare?'<a href="#comparativa">Antes y después</a>':''}<a href="#consulta">Tu consulta</a><a href="#dudas">Dudas frecuentes</a></nav>
<section class="service-intro-v5 section" id="sobre"><div><span class="eyebrow">PARA EMPEZAR</span><h2>${esc(service.hero)}</h2></div><div class="service-prose"><p>${esc(service.lead)}</p><p>${esc(service.second)}</p>${service.tentative?'<p class="availability">Confirma con Lumis la disponibilidad de este servicio antes de considerarlo definitivo.</p>':''}</div></section>
<section class="context section" id="cuando"><div class="context-title"><span class="eyebrow">TU ESPACIO, TU CASO</span><h2>Puede tener sentido<br><em>si estás pensando en…</em></h2><p>Estas son situaciones orientativas. El alcance concreto se decide al hablar con Lumis.</p></div><div class="context-cards">${service.contexts.map((context,i)=>`<article><span>0${i+1}</span><h3>${esc(context)}</h3>${icon('sparkle',27)}</article>`).join('')}</div></section>
${service.compare?`<section class="service-change section" id="comparativa"><div><span class="eyebrow">MISMA ESCENA · DOS MOMENTOS</span><h2>Una diferencia<br><em>que se ve.</em></h2><p>Esta comparativa es una recreación ilustrativa. No muestra un trabajo real de Limpiezas Lumis.</p><p class="compare-help">Arrastra el control o usa las flechas del teclado.</p></div>${compare(service.compare[0],service.compare[1],service.name.toLowerCase())}</section>`:''}
<section class="inquiry section" id="consulta"><div class="inquiry-photo">${photo(firstImage,`Detalle ilustrativo relacionado con ${service.name.toLowerCase()}`)}<span>Ejemplo visual ilustrativo</span></div><div class="inquiry-copy"><span class="eyebrow">PARA PEDIR PRESUPUESTO</span><h2>Cuéntanos<br><em>lo esencial.</em></h2><p>No necesitas tenerlo todo resuelto. Estos datos ayudan a empezar con una idea más clara:</p><ul>${service.details.map(detail=>`<li>${icon('arrow',18)} ${esc(detail)}</li>`).join('')}</ul><a class="button button-primary" href="${wa(message)}" target="_blank" rel="noopener">Preparar consulta por WhatsApp ${icon('north',19)}</a></div></section>
<section class="care-tip section"><span>UNA IDEA PARA EMPEZAR / ${service.number}</span><p>${esc(service.care)}</p></section>
<section class="service-gallery-v5 section"><div class="section-heading"><span class="eyebrow">MIRA MÁS DE CERCA</span><h2>El espacio<br><em>en imágenes.</em></h2><p>Ejemplos visuales creados para esta demostración. No son fotografías de trabajos realizados por Lumis.</p></div><div class="gallery-v5"><figure>${photo(service.image,`${service.name}, ejemplo visual ilustrativo`)}<figcaption>${esc(service.name)} · Escena ilustrativa</figcaption></figure><figure>${photo(firstImage,`${service.name}, vista complementaria ilustrativa`)}<figcaption>Una mirada al detalle</figcaption></figure><figure>${photo(secondImage,`${service.name}, otro espacio ilustrativo`)}<figcaption>Otra perspectiva</figcaption></figure></div></section>
<section class="faq section" id="dudas"><div><span class="eyebrow">PREGUNTAS FRECUENTES</span><h2>Resolvamos<br><em>tus dudas.</em></h2><p>Y si tu caso no aparece aquí, cuéntanoslo directamente.</p></div><div class="faq-list">${service.faqs.map(([q,a])=>`<details><summary>${esc(q)} ${icon('plus',20)}</summary><p>${esc(a)}</p></details>`).join('')}</div></section>
<section class="related section"><div class="related-head"><span class="eyebrow">QUIZÁ TAMBIÉN TE INTERESE</span><h2>Un espacio lleva<br><em>a otro.</em></h2></div><div class="related-grid">${service.related.map(slug=>{const related=bySlug(slug);return `<a href="${slug}.html">${photo(related.image,related.name)}<span>${esc(related.name)} ${icon('north',20)}</span></a>`}).join('')}</div><a class="all-services" href="index.html#servicios">Ver los 16 servicios ${icon('arrow',19)}</a></section></main>${footer(service.slug)}`;
  fs.writeFileSync(`${service.slug}.html`,html);
}

home(); services.forEach(page);
console.log(`Sitio generado: portada y ${services.length} páginas de servicio.`);
